[package]
name = "floating_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.6.0"
iced_aw = { git="https://github.com/iced-rs/iced_aw", features=["floating_element"]}
